### ISSUE TITLE
p.65 그림 1.10에 대한 질문

### ISSUE THREAD

**Issue by tmznwnel00** [wjrmffldrhrl/Kubernetes-Study#1]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/65274009/172613003-82a6b637-8805-419e-bef0-842f23e18214.png">

- 도형이 컨테이너 이미지, 도형을 박스로 감싸면 컨테이너로 이해했는데 오른쪽에 한 박스안에 두 도형이 들어있는 그림은
한 컨테이너에 두 컨테이너 이미지가 들어있는 형식이 아닌 설명처럼 두 컨테이너가 함께 실행되는 형식인가요?

**Comment by wjrmffldrhrl** [comment]
아직 1장에서는 나오지 않는 개념인 Pod 입니다.

쿠버네티스에서 생성하고 관리할 수 있는 배포 가능한 가장 작은 컴퓨팅 단위로 Pod를 사용중이고 Pod에는 한 개 이상의 컨테이너가 포함될 수 있습니다.

**Comment by tmznwnel00** [comment]
여러 컨테이너가 맞았네용 감사합니당

**Comment by tmznwnel00** [comment]
아 이거 바로 앞장에 설명 있었네용.. ㅋㅋ
