### ISSUE TITLE
7th Kubernetes Study, 2022-07-21 스터디 

### ISSUE THREAD

**Issue by ikswary** [wjrmffldrhrl/Kubernetes-Study#11]
질문 공유용 임시 이슈입니다

**Comment by wjrmffldrhrl** [comment]
# 6. 볼륨

감사합니다.  

요즘 정신이 없어서 이슈 생성과 질문 준비를 못했네요 😢 

질문 준비되는대로 올려주시면 답변 한번 준비해보겠습니다.

**Comment by ikswary** [comment]
PV를 만들때 특정 물리 저장 매체를 의존하고 그렇게 만들어진 PV를 PVC에 바인딩을 하는 방식으로 파드에 저장장치를 연동하게 되어있는데 제가 이해하기로는 한 PVC가 PV와 바인딩 되면 해당 PV는 동시에 다른 PVC와는 바인딩이 안된다고 이해했습니다.

그런데 PV 스펙에 최대 용량이 있고 PVC에 최소 요구 용량을 갖는 구조를 취하고 있는데
PV는 동시에 다른 PVC와 바인딩이 될수 있어야 위 구조를 효율적으로 사용할 수 있을것이고
또 다른 k8s의 리소스들이 서로 갖는 관계와 유사해진다고 생각하는데요
PV와 PVC 바인딩은 유니크하다는것이 제가 잘못 이해한건지 아니면 다른 방법이 있는건지 궁금합니다

**Comment by wjrmffldrhrl** [comment]
이번 회차는 양이 적고 인원도 4명뿐이라 질의응답 대신에 내용을 조금 자세히 다뤄봐야겠네요

그래도 각자 가슴속에 질문 1~2개씩 들고 스터디때 만나봐요 🥲

**Comment by wjrmffldrhrl** [comment]
> PV를 만들때 특정 물리 저장 매체를 의존하고 그렇게 만들어진 PV를 PVC에 바인딩을 하는 방식으로 파드에 저장장치를 연동하게 되어있는데 제가 이해하기로는 한 PVC가 PV와 바인딩 되면 해당 PV는 동시에 다른 PVC와는 바인딩이 안된다고 이해했습니다.
> 
> 그런데 PV 스펙에 최대 용량이 있고 PVC에 최소 요구 용량을 갖는 구조를 취하고 있는데 PV는 동시에 다른 PVC와 바인딩이 될수 있어야 위 구조를 효율적으로 사용할 수 있을것이고 또 다른 k8s의 리소스들이 서로 갖는 관계와 유사해진다고 생각하는데요 PV와 PVC 바인딩은 유니크하다는것이 제가 잘못 이해한건지 아니면 다른 방법이 있는건지 궁금합니다

저도 책 읽어보면서 PVC가 PV를 사용중일때는 다른 사용자는 사용 불가능한 것으로 이해했는데 비효율적으로 사용될 여지가 보이긴 하네요

**Comment by wjrmffldrhrl** [comment]
> PV를 만들때 특정 물리 저장 매체를 의존하고 그렇게 만들어진 PV를 PVC에 바인딩을 하는 방식으로 파드에 저장장치를 연동하게 되어있는데 제가 이해하기로는 한 PVC가 PV와 바인딩 되면 해당 PV는 동시에 다른 PVC와는 바인딩이 안된다고 이해했습니다.
> 
> 그런데 PV 스펙에 최대 용량이 있고 PVC에 최소 요구 용량을 갖는 구조를 취하고 있는데 PV는 동시에 다른 PVC와 바인딩이 될수 있어야 위 구조를 효율적으로 사용할 수 있을것이고 또 다른 k8s의 리소스들이 서로 갖는 관계와 유사해진다고 생각하는데요 PV와 PVC 바인딩은 유니크하다는것이 제가 잘못 이해한건지 아니면 다른 방법이 있는건지 궁금합니다

단순히 PV는 필요한 만큼 생성해 두고 PVC의 requests 용량은 PV가 충분한 용량을 가지고 있는지 체크하는 용도같습니다.

**Comment by wjrmffldrhrl** [comment]
![image](https://user-images.githubusercontent.com/49122299/180106641-9bd82b6d-4af4-41cd-b628-991f38698a97.png)
