### ISSUE TITLE
p.97 파드에 대한 설명중 질문

### ISSUE THREAD

**Issue by tmznwnel00** [wjrmffldrhrl/Kubernetes-Study#3]
<img width="594" alt="image" src="https://user-images.githubusercontent.com/65274009/173360279-376b0293-40f9-4692-8912-b6a5de1cad16.png">

한 워커노드에 여러개의 파드들이 실행가능한가요?

**Comment by tmznwnel00** [comment]
바로 뒷장에 나오네요 ㅋ

**Comment by tmznwnel00** [comment]
<img width="609" alt="image" src="https://user-images.githubusercontent.com/65274009/173360581-8233b429-105a-44c8-aedd-95f38a89009e.png">

**Comment by tmznwnel00** [comment]
왜 굳이 다른 워커노드에 다른 파드를 실행시켜서 격리안시키고 한 워커노드에 여러 파드를 넣어둘까요?

**Comment by wjrmffldrhrl** [comment]
어떤 노드에 어떤 파드가 생성될지는 쿠버네티스가 스케줄링 할거에요  

쿠버네티스를 사용하는 이유중에 하나가 노드들의 리소스를 효율적으로 사용하기 위해서인데, 노드에 파드를 생성할 수 있는 리소스가 남아있다면 쿠버네티스는 그걸 사용할겁니다.

**Comment by wjrmffldrhrl** [comment]
이후에 그런 스케줄링을 제한하는 방법도 나올거에요

**Comment by tmznwnel00** [comment]
아 쿠버가 리소스를 효율적으로 사용하기 위해 노드에 남는 리소스가 있으면 파드를 더 추가할수도있겠네요
감사합니다!
